Repository Team-Oriddle/oriddle-backend, pull requests merged in 2024-03, with the labels that each got.

#33 [feat/#25] 퀴즈방 정보 조회 API 구현
  src/main/kotlin/com/tuk/oriddle/domain/participant/dto/ParticipantInfoGetResponse.kt
  src/main/kotlin/com/tuk/oriddle/domain/participant/repository/ParticipantRepository.kt
  src/main/kotlin/com/tuk/oriddle/domain/participant/service/ParticipantQueryService.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/controller/QuizRoomController.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/dto/response/QuizRoomCreateResponse.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/dto/response/QuizRoomInfoGetResponse.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/dto/response/QuizRoomJoinResponse.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/service/QuizRoomService.kt
  src/main/kotlin/com/tuk/oriddle/global/result/ResultCode.kt
Labels: 기능구현

#35 [feat/#34] 로그아웃 기능 구현
  src/main/kotlin/com/tuk/oriddle/global/config/SecurityConfig.kt
Labels: 기능구현

#36 [ feat/#32] 퀴즈방 시작 API 구현
  build.gradle.kts
  docker-compose.yml
  src/main/kotlin/com/tuk/oriddle/OriddleApplication.kt
  src/main/kotlin/com/tuk/oriddle/domain/question/entity/Question.kt
  src/main/kotlin/com/tuk/oriddle/domain/question/repository/QuestionRepository.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/controller/QuizRoomController.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/dto/message/QuestionMessage.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/dto/message/StartQuizRoomMessage.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/dto/redis/QuestionRedisDto.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/dto/redis/QuizStatusRedisDto.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/dto/redis/UserRedisDto.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/dto/request/QuizRoomCreateRequest.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/entity/QuizProgressStatus.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/exception/QuestionNotFoundInRedisException.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/exception/QuizStatusNotFoundInRedisException.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/scheduler/QuizRoomScheduler.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/service/QuizRoomMessageService.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/service/QuizRoomQueryService.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/service/QuizRoomRedisService.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/service/QuizRoomService.kt
  src/main/kotlin/com/tuk/oriddle/global/config/RedisConfig.kt
  src/main/kotlin/com/tuk/oriddle/global/error/ErrorCode.kt
  src/main/kotlin/com/tuk/oriddle/global/result/ResultCode.kt
  src/main/resources/application.yml
Labels: 환경설정, 기능구현

#40 [feat/#37] 퀴즈 정답 확인 API 구현 및 redis 조회 시 repository 계층을 사용하도록 리팩토링
  src/main/kotlin/com/tuk/oriddle/domain/answer/dto/redis/AnswerRedisDto.kt
  src/main/kotlin/com/tuk/oriddle/domain/answer/exception/AnswerNotFoundInRedisException.kt
  src/main/kotlin/com/tuk/oriddle/domain/answer/repository/AnswerRedisRepository.kt
  src/main/kotlin/com/tuk/oriddle/domain/answer/service/AnswerRedisService.kt
  src/main/kotlin/com/tuk/oriddle/domain/participant/dto/redis/ParticipantRedisDto.kt
  src/main/kotlin/com/tuk/oriddle/domain/participant/dto/redis/ParticipantsRedisDto.kt
  src/main/kotlin/com/tuk/oriddle/domain/participant/repository/ParticipantRedisRepository.kt
  src/main/kotlin/com/tuk/oriddle/domain/participant/service/ParticipantRedisService.kt
  src/main/kotlin/com/tuk/oriddle/domain/question/dto/redis/QuestionRedisDto.kt
  src/main/kotlin/com/tuk/oriddle/domain/question/exception/QuestionNotFoundInRedisException.kt
  src/main/kotlin/com/tuk/oriddle/domain/question/repository/QuestionRedisRepository.kt
  src/main/kotlin/com/tuk/oriddle/domain/question/service/QuestionRedisService.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/controller/QuizRoomWsController.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/dto/message/AnswerCorrectMessage.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/dto/message/CheckAnswerMessage.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/dto/message/QuestionMessage.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/dto/redis/QuestionRedisDto.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/dto/redis/QuizRoomStatusRedisDto.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/dto/redis/QuizStatusRedisDto.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/dto/redis/UserRedisDto.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/exception/QuizRoomStatusNotFoundInRedisException.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/repository/QuizRoomStatusRedisRepository.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/scheduler/QuizRoomScheduler.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/service/QuizRoomMessageService.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/service/QuizRoomRedisService.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/service/QuizRoomService.kt
  src/main/kotlin/com/tuk/oriddle/global/config/RedisConfig.kt
  src/main/kotlin/com/tuk/oriddle/global/config/WebSocketConfig.kt
  src/main/kotlin/com/tuk/oriddle/global/error/ErrorCode.kt
  src/main/kotlin/com/tuk/oriddle/global/interceptor/CustomHttpSessionHandShakeInterceptor.kt
Labels: 리팩토링, 기능구현

#43 [feat/#42] 퀴즈방 참가자들의 방장 여부 기능 추가
  src/main/kotlin/com/tuk/oriddle/domain/participant/dto/ParticipantInfoGetResponse.kt
  src/main/kotlin/com/tuk/oriddle/domain/participant/entity/Participant.kt
  src/main/kotlin/com/tuk/oriddle/domain/participant/exception/ParticipantNotHostException.kt
  src/main/kotlin/com/tuk/oriddle/domain/participant/repository/ParticipantRepository.kt
  src/main/kotlin/com/tuk/oriddle/domain/participant/service/ParticipantQueryService.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/controller/QuizRoomController.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/service/QuizRoomService.kt
  src/main/kotlin/com/tuk/oriddle/domain/user/controller/UserController.kt
  src/main/kotlin/com/tuk/oriddle/domain/user/service/UserService.kt
  src/main/kotlin/com/tuk/oriddle/global/error/ErrorCode.kt
Labels: 기능구현

#46 [feat/#45] 퀴즈방 채팅 메시징 구현
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/controller/QuizRoomWsController.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/dto/message/ChatReceiveMessage.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/dto/message/ChatSendMessage.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/service/QuizRoomMessageService.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/service/QuizRoomProgressService.kt
Labels: 기능구현

#48 [refactor/#47] 로그인한 userId 불러오는 방식 개선, 코드 포매팅 및 리팩토링
  src/main/kotlin/com/tuk/oriddle/OriddleApplication.kt
  src/main/kotlin/com/tuk/oriddle/domain/participant/dto/ParticipantInfoGetResponse.kt
  src/main/kotlin/com/tuk/oriddle/domain/quiz/controller/QuizController.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/controller/QuizRoomController.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/controller/QuizRoomWsController.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/dto/request/QuizRoomCreateRequest.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/service/QuizRoomMessageService.kt
  src/main/kotlin/com/tuk/oriddle/domain/user/controller/UserController.kt
  src/main/kotlin/com/tuk/oriddle/domain/user/entity/Modifier.kt
  src/main/kotlin/com/tuk/oriddle/domain/user/service/UserQueryService.kt
  src/main/kotlin/com/tuk/oriddle/domain/user/service/UserService.kt
  src/main/kotlin/com/tuk/oriddle/global/annotation/LoginUser.kt
  src/main/kotlin/com/tuk/oriddle/global/config/WebMvcConfig.kt
  src/main/kotlin/com/tuk/oriddle/global/error/GlobalExceptionHandler.kt
  src/main/kotlin/com/tuk/oriddle/global/oauth/CustomAuthenticationSuccessHandler.kt
  src/main/kotlin/com/tuk/oriddle/global/resolver/LoginUserArgumentResolver.kt
  src/main/kotlin/com/tuk/oriddle/global/result/ResultCode.kt
Labels: 리팩토링

#51 [refactor/#49] Quiz, User, QuizRoom 관련 API Swagger 문서 작성 및 기타 리팩토링 진행
  src/main/kotlin/com/tuk/oriddle/domain/quiz/controller/QuizController.kt
  src/main/kotlin/com/tuk/oriddle/domain/quiz/controller/doc/QuizApiDoc.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/controller/QuizRoomController.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/controller/doc/QuizRoomApiDoc.kt
  src/main/kotlin/com/tuk/oriddle/domain/user/controller/UserController.kt
  src/main/kotlin/com/tuk/oriddle/domain/user/controller/doc/UserApiDoc.kt
Labels: 리팩토링

#53 [ feat/#50] 퀴즈방 생성 시 RequestBody에 대한 유효성 검증 추가
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/dto/request/QuizRoomCreateRequest.kt
  src/main/kotlin/com/tuk/oriddle/global/config/WebMvcConfig.kt
  src/main/kotlin/com/tuk/oriddle/global/error/ErrorResponse.kt
  src/main/kotlin/com/tuk/oriddle/global/error/GlobalExceptionHandler.kt
Labels: 기능구현

#55 [refactor/#54] 유저와 참가자 도메인의 연관관계 수정 및 퀴즈방 관련 API 예외처리 로직 추가
  src/main/kotlin/com/tuk/oriddle/domain/participant/entity/Participant.kt
  src/main/kotlin/com/tuk/oriddle/domain/participant/repository/ParticipantRepository.kt
  src/main/kotlin/com/tuk/oriddle/domain/participant/service/ParticipantQueryService.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/controller/QuizRoomController.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/controller/doc/QuizRoomApiDoc.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/exception/UserAlreadyInQuizRoomException.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/service/QuizRoomProgressService.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/service/QuizRoomService.kt
  src/main/kotlin/com/tuk/oriddle/global/error/ErrorCode.kt
Labels: 리팩토링, 기능구현

#59 [ fix/#57] 예외 & 에러코드 수정
  src/main/kotlin/com/tuk/oriddle/domain/participant/service/ParticipantQueryService.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/exception/QuizRoomFullException.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/exception/UserAlreadyInCurrentQuizRoomException.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/exception/UserAlreadyInOtherQuizRoomException.kt
  src/main/kotlin/com/tuk/oriddle/domain/quizroom/service/QuizRoomService.kt
  src/main/kotlin/com/tuk/oriddle/global/error/ErrorCode.kt
  src/main/kotlin/com/tuk/oriddle/global/result/ResultCode.kt
Labels: 오류수정
